// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Upload a local client file into Codex-managed host storage.
 */
export type FsUploadFileParams = {
/**
 * User-visible file name. App-server stores only the final path component.
 */
fileName: string,
/**
 * File contents encoded as base64.
 */
dataBase64: string, };
