// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Codex-managed host path created by `fs/uploadFile`.
 */
export type FsUploadFileResponse = {
/**
 * Absolute path to the uploaded file on the app-server host.
 */
path: AbsolutePathBuf, };
